version: "3"

services:

    php-fpm:
        build: ./Dockerfiles/php-fpm
        working_dir: /var/www/
        container_name: 'symfony-php-fpm'
        ports:
            - "81:80"
        volumes:
            - ./Symfony:/var/www/

    apache:
        build: ./Dockerfiles/webserver
        container_name: symfony-apache
        volumes:
            - ./Apache:/etc/apache2/sites-enabled
            - ./Symfony:/var/www/
        ports:
            - "82:80"

#    mysql:
#        image:  mysql:5.7
#        container_name: symfony-mysql
#        working_dir: /var/www/
#        ports:
#            - "83:80"
