version: "3"

services:

    php-fpm:
        build: ./Dockerfiles/php-fpm
        working_dir: /var/www/
        container_name: 'symfony-php-fpm'
        ports:
            - "81:80"
        volumes:
            - ./Symfony:/var/www/
    apache:
        build: ./Dockerfiles/webserver
        container_name: symfony-apache
        volumes:
            - ./Apache:/etc/apache2/sites-enabled
            - ./Symfony:/var/www/
        ports:
            - "82:80"
    mysql:
        image:  mysql:5.7
        container_name: symfony-mysql
        environment:
            MYSQL_ROOT_PASSWORD: pasforsymfony
            MYSQL_DATABASE: pasforsymfony
            MYSQL_USER: pasforsymfony
            MYSQL_PASSWORD: pasforsymfony
        volumes:
            - ./Mysql/data/mysql:/var/lib/mysql
            - ./Logs/mysql:/var/log/mysql
        ports:
            - "83:80"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'symfony-phpmyadmin'
        environment:
          PMA_HOST: symfony-mysql
          PMA_PORT: 3306
        ports:
          - '84:80'